name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Установка sshpass
        run: sudo apt-get install -y sshpass

      - name: Деплой на сервер
        env:
          SSH_PASSWORD: bex2009ake
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@45.138.158.251 "cd /var/www/deploy && git pull origin main && systemctl restart deploy"
